name: StepNumber and StepName

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests pytest allure-pytest

      - name: Run pytest and collect Allure results
        id: run_tests
        run: |
          mkdir -p allure-results
          export PYTHONPATH=$PYTHONPATH:$(pwd)/MainFolder
          pytest --alluredir=allure-results --disable-warnings -q || echo "Tests failed"
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      - name: Setup Java (required by Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Allure CLI
        run: |
          ALLURE_VERSION=2.21.0
          wget -q -O /tmp/allure.zip "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip"
          unzip -q /tmp/allure.zip -d /tmp
          echo "/tmp/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH

      - name: Generate Allure HTML Report
        run: |
          allure generate allure-results -o allure-report --clean || echo "Report generation failed"

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload generated Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Fail workflow if tests failed
        if: steps.run_tests.outputs.exit_code != '0'
        run: exit 1
