name: CI - pytest + Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest 

      - name: Run pytest and collect Allure results
        run: |
          mkdir -p reports/allure-results
          export PYTHONPATH=$PYTHONPATH:$(pwd)/MainFolder
          pytest --maxfail=1 --disable-warnings -q --alluredir=reports/allure-results

        continue-on-error: false

      # Install Java (required by Allure CLI) using actions/setup-java
      - name: Setup Java (required for Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'    # Eclipse Temurin (AdoptOpenJDK successor)
          java-version: '11'

      - name: Install Allure CLI
        run: |
          # choose an Allure CLI version; adjust if you want a different one
          ALLURE_VERSION=2.21.0
          wget -q -O /tmp/allure.zip "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip"
          unzip -q /tmp/allure.zip -d /tmp
          echo "/tmp/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH

      - name: Generate Allure HTML Report
        run: |
          # generate HTML report from results; creates reports/allure-report
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      - name: Upload generated Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
